// <auto-generated />
using API_Reclutamiento.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Reclutamiento.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250327012907_FixPostulanteDomicilioRelation")]
    partial class FixPostulanteDomicilioRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Reclutamiento.Models.Domicilio", b =>
                {
                    b.Property<int>("DomicilioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DomicilioId"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.HasKey("DomicilioId");

                    b.HasIndex("PostulanteId")
                        .IsUnique();

                    b.ToTable("Domicilios");
                });

            modelBuilder.Entity("API_Reclutamiento.Models.Postulante", b =>
                {
                    b.Property<int>("PostulanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostulanteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PostulanteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Postulantes");
                });

            modelBuilder.Entity("API_Reclutamiento.Models.Domicilio", b =>
                {
                    b.HasOne("API_Reclutamiento.Models.Postulante", "Postulante")
                        .WithOne("Domicilio")
                        .HasForeignKey("API_Reclutamiento.Models.Domicilio", "PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("API_Reclutamiento.Models.Postulante", b =>
                {
                    b.Navigation("Domicilio")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
