// <auto-generated />
using System;
using API_Reclutamiento.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Reclutamiento.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250419122821_prueba Navegacion")]
    partial class pruebaNavegacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Reclutamiento.Models.Domicilio", b =>
                {
                    b.Property<int>("DomicilioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DomicilioId"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostulanteId")
                        .HasColumnType("int");

                    b.HasKey("DomicilioId");

                    b.HasIndex("PostulanteId");

                    b.ToTable("Domicilios");
                });

            modelBuilder.Entity("API_Reclutamiento.Models.Nacionalidad", b =>
                {
                    b.Property<int>("IdNacionalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNacionalidad"));

                    b.Property<string>("NombreNacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNacionalidad");

                    b.ToTable("Nacionalidades");
                });

            modelBuilder.Entity("API_Reclutamiento.Models.Postulante", b =>
                {
                    b.Property<int>("PostulanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostulanteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date");

                    b.Property<int>("IdNacionalidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PostulanteId");

                    b.HasIndex("IdNacionalidad");

                    b.ToTable("Postulantes");
                });

            modelBuilder.Entity("API_Reclutamiento.Models.Domicilio", b =>
                {
                    b.HasOne("API_Reclutamiento.Models.Postulante", "Postulante")
                        .WithMany("Domicilios")
                        .HasForeignKey("PostulanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulante");
                });

            modelBuilder.Entity("API_Reclutamiento.Models.Postulante", b =>
                {
                    b.HasOne("API_Reclutamiento.Models.Nacionalidad", "Nacionalidad")
                        .WithMany("Postulantes")
                        .HasForeignKey("IdNacionalidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nacionalidad");
                });

            modelBuilder.Entity("API_Reclutamiento.Models.Nacionalidad", b =>
                {
                    b.Navigation("Postulantes");
                });

            modelBuilder.Entity("API_Reclutamiento.Models.Postulante", b =>
                {
                    b.Navigation("Domicilios");
                });
#pragma warning restore 612, 618
        }
    }
}
